2020-10-20 20:21:47,775          root     INFO: Starting script
2020-10-20 20:21:48,619          root     INFO: Parsing Folha de S.Paulo - Opinião - Principal
2020-10-20 20:21:49,300          root     INFO: Parsing Folha de S.Paulo - Poder - Principal
2020-10-20 20:21:49,976          root     INFO: Parsing Folha de S.Paulo - Ambiente - Principal
2020-10-20 20:21:50,193          root     INFO: Parsing R7 - Brasil
2020-10-20 20:21:50,577          root     INFO: <del>Condenado</del> <ins>?Condenado</ins> por estupro pela Justiça italiana, Robinho sacudiu as redes sociais com declarações revoltantes extraídas de interceptações telefônicas e entrevistas. Enquanto feminista, o que mais me revolta é ser obrigada a concordar com alguns trechos. Antes que me cancelem, vamos a eles. Leia mais (10/19/2020 - 23h15)
2020-10-20 20:21:52,446          root     INFO: Media ready with ids: 1318648649925132288
2020-10-20 20:21:52,447          root     INFO: Text to tweet: Modificação da Descrição
2020-10-20 20:21:52,447          root     INFO: Article id: https://redir.folha.com.br/redir/online/opiniao/rss091/*https://www1.folha.uol.com.br/colunas/manuela-cantuaria/2020/10/homens-como-robinho-fazem-com-que-o-feminismo-infelizmente-precise-existir.shtml
2020-10-20 20:21:52,452          root     INFO: Tweeting url: https://redir.folha.com.br/redir/online/opiniao/rss091/*https://www1.folha.uol.com.br/colunas/manuela-cantuaria/2020/10/homens-como-robinho-fazem-com-que-o-feminismo-infelizmente-precise-existir.shtml
2020-10-20 20:21:52,583          root    ERROR: Tweet text failed
Traceback (most recent call last):
  File "nytdiff.py", line 131, in tweet_text
    tweet_id = self.api.update_status(status=text)
  File "/home/runner/work/NYTdiff/NYTdiff/venv/lib/python3.6/site-packages/tweepy/api.py", line 215, in update_status
    )(*args, **kwargs)
  File "/home/runner/work/NYTdiff/NYTdiff/venv/lib/python3.6/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/home/runner/work/NYTdiff/NYTdiff/venv/lib/python3.6/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 187, 'message': 'Status is a duplicate.'}]
2020-10-20 20:21:52,587          root    ERROR: Error tweeting for article_id:
'bool' object has no attribute 'id'
Traceback (most recent call last):
  File "nytdiff.py", line 151, in tweet
    reply_to = tweet.id if not TESTING else time.time()
AttributeError: 'bool' object has no attribute 'id'
2020-10-20 20:21:53,731          root     INFO: New article tracked: https://redir.folha.com.br/redir/online/poder/rss091/*https://www1.folha.uol.com.br/colunas/painel/2020/10/candidatos-do-psl-levantam-suspeita-sobre-repasse-de-r-690-mil-a-ex-mulher-de-ministro-do-turismo.shtml
2020-10-20 20:21:53,758          root     INFO: Em reunião com governadores nesta terça-feira (20), o ministro da Saúde, Eduardo Pazuello, afirmou que vai incorporar a vacina desenvolvida pelo Instituto Butantan, em São Paulo, no Programa Nacional de Imunizações, colocando-a assim no cronograma <del>nacional.</del> <ins>do governo federal.</ins> Leia mais (10/20/2020 - 15h41)
2020-10-20 20:21:55,550          root     INFO: Media ready with ids: 1318648663233744898
2020-10-20 20:21:55,551          root     INFO: Text to tweet: Modificação da Descrição
2020-10-20 20:21:55,551          root     INFO: Article id: https://redir.folha.com.br/redir/online/poder/rss091/*https://www1.folha.uol.com.br/colunas/painel/2020/10/ministerio-da-saude-anuncia-que-vai-incorporar-vacina-chinesa-em-calendario-nacional.shtml
2020-10-20 20:21:55,557          root     INFO: Tweeting url: https://redir.folha.com.br/redir/online/poder/rss091/*https://www1.folha.uol.com.br/colunas/painel/2020/10/ministerio-da-saude-anuncia-que-vai-incorporar-vacina-chinesa-em-calendario-nacional.shtml
2020-10-20 20:21:55,659          root    ERROR: Tweet text failed
Traceback (most recent call last):
  File "nytdiff.py", line 131, in tweet_text
    tweet_id = self.api.update_status(status=text)
  File "/home/runner/work/NYTdiff/NYTdiff/venv/lib/python3.6/site-packages/tweepy/api.py", line 215, in update_status
    )(*args, **kwargs)
  File "/home/runner/work/NYTdiff/NYTdiff/venv/lib/python3.6/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/home/runner/work/NYTdiff/NYTdiff/venv/lib/python3.6/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 187, 'message': 'Status is a duplicate.'}]
2020-10-20 20:21:55,659          root    ERROR: Error tweeting for article_id:
'bool' object has no attribute 'id'
Traceback (most recent call last):
  File "nytdiff.py", line 151, in tweet
    reply_to = tweet.id if not TESTING else time.time()
AttributeError: 'bool' object has no attribute 'id'
2020-10-20 20:21:55,773          root     INFO: <del>Candidato à Prefeitura de Porto Alegre, José Fortunati participa da</del> <ins>Em</ins> sabatina <del>Folha/UOL</del> <ins>Folha/UOL, Fortunati diz que Marchezan usa fake news para esconder incompetência</ins>
2020-10-20 20:21:57,490          root     INFO: Media ready with ids: 1318648671450337280
2020-10-20 20:21:57,490          root     INFO: Text to tweet: Modificação do Título
2020-10-20 20:21:57,491          root     INFO: Article id: https://redir.folha.com.br/redir/online/poder/rss091/*https://www1.folha.uol.com.br/poder/2020/10/candidato-a-prefeitura-de-porto-alegre-jose-fortunati-participa-da-sabatina-folhauol.shtml
2020-10-20 20:21:57,498          root     INFO: Tweeting url: https://redir.folha.com.br/redir/online/poder/rss091/*https://www1.folha.uol.com.br/poder/2020/10/candidato-a-prefeitura-de-porto-alegre-jose-fortunati-participa-da-sabatina-folhauol.shtml
2020-10-20 20:21:57,599          root    ERROR: Tweet text failed
Traceback (most recent call last):
  File "nytdiff.py", line 131, in tweet_text
    tweet_id = self.api.update_status(status=text)
  File "/home/runner/work/NYTdiff/NYTdiff/venv/lib/python3.6/site-packages/tweepy/api.py", line 215, in update_status
    )(*args, **kwargs)
  File "/home/runner/work/NYTdiff/NYTdiff/venv/lib/python3.6/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/home/runner/work/NYTdiff/NYTdiff/venv/lib/python3.6/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 187, 'message': 'Status is a duplicate.'}]
2020-10-20 20:21:57,600          root    ERROR: Error tweeting for article_id:
'bool' object has no attribute 'id'
Traceback (most recent call last):
  File "nytdiff.py", line 151, in tweet
    reply_to = tweet.id if not TESTING else time.time()
AttributeError: 'bool' object has no attribute 'id'
2020-10-20 20:21:57,600          root     INFO: <del>A Folha, em parceria com o UOL, sabatina nesta terça-feira (20) José Fortunati, que se lançou pelo PTB à Prefeitura</del> <ins>O ex-prefeito</ins> de Porto <del>Alegre.</del> <ins>Alegre José Fortunati (PTB), novamente candidato, disse que o atual mandatário da capital gaúcha, Nelson Marchezan Júnior (PSDB), "gosta de fake news".</ins> Leia mais (10/20/2020 - 12h05)
2020-10-20 20:21:59,352          root     INFO: Media ready with ids: 1318648679021109249
2020-10-20 20:21:59,352          root     INFO: Text to tweet: Modificação da Descrição
2020-10-20 20:21:59,352          root     INFO: Article id: https://redir.folha.com.br/redir/online/poder/rss091/*https://www1.folha.uol.com.br/poder/2020/10/candidato-a-prefeitura-de-porto-alegre-jose-fortunati-participa-da-sabatina-folhauol.shtml
2020-10-20 20:21:59,358          root     INFO: Tweeting url: https://redir.folha.com.br/redir/online/poder/rss091/*https://www1.folha.uol.com.br/poder/2020/10/candidato-a-prefeitura-de-porto-alegre-jose-fortunati-participa-da-sabatina-folhauol.shtml
2020-10-20 20:21:59,461          root    ERROR: Tweet text failed
Traceback (most recent call last):
  File "nytdiff.py", line 131, in tweet_text
    tweet_id = self.api.update_status(status=text)
  File "/home/runner/work/NYTdiff/NYTdiff/venv/lib/python3.6/site-packages/tweepy/api.py", line 215, in update_status
    )(*args, **kwargs)
  File "/home/runner/work/NYTdiff/NYTdiff/venv/lib/python3.6/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/home/runner/work/NYTdiff/NYTdiff/venv/lib/python3.6/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 187, 'message': 'Status is a duplicate.'}]
2020-10-20 20:21:59,461          root    ERROR: Error tweeting for article_id:
'bool' object has no attribute 'id'
Traceback (most recent call last):
  File "nytdiff.py", line 151, in tweet
    reply_to = tweet.id if not TESTING else time.time()
AttributeError: 'bool' object has no attribute 'id'
2020-10-20 20:22:02,035          root     INFO: Removed https://redir.folha.com.br/redir/online/poder/rss091/*https://www1.folha.uol.com.br/colunas/painel/2020/10/conselheiro-de-seguranca-de-trump-chega-domingo-no-brasil.shtml
2020-10-20 20:22:02,036          root     INFO: Finished script
<class 'tweepy.error.TweepError'>
<class 'tweepy.error.TweepError'>
<class 'tweepy.error.TweepError'>
<class 'tweepy.error.TweepError'>
